# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'AMSInterface.ui'
##
## Created by: Qt User Interface Compiler version 6.4.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFormLayout, QGridLayout,
    QLabel, QLineEdit, QMainWindow, QSizePolicy,
    QSpacerItem, QTabWidget, QWidget)

class Ui_AMS_Interface(object):
    def setupUi(self, AMS_Interface):
        if not AMS_Interface.objectName():
            AMS_Interface.setObjectName(u"AMS_Interface")
        AMS_Interface.resize(803, 595)
        AMS_Interface.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QWidget(AMS_Interface)
        self.centralwidget.setObjectName(u"centralwidget")
        self.primaryTabWidget = QTabWidget(self.centralwidget)
        self.primaryTabWidget.setObjectName(u"primaryTabWidget")
        self.primaryTabWidget.setGeometry(QRect(0, 0, 800, 600))
        palette = QPalette()
        brush = QBrush(QColor(255, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(0, 0, 0, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
        self.primaryTabWidget.setPalette(palette)
        self.tab1 = QWidget()
        self.tab1.setObjectName(u"tab1")
        self.tab1.setMinimumSize(QSize(0, 452))
        self.PredicttionTabWidget = QTabWidget(self.tab1)
        self.PredicttionTabWidget.setObjectName(u"PredicttionTabWidget")
        self.PredicttionTabWidget.setGeometry(QRect(0, 0, 800, 570))
        palette1 = QPalette()
        brush2 = QBrush(QColor(0, 0, 255, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        brush3 = QBrush(QColor(214, 118, 118, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        self.PredicttionTabWidget.setPalette(palette1)
        self.Geometriadocordo = QWidget()
        self.Geometriadocordo.setObjectName(u"Geometriadocordo")
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        brush4 = QBrush(QColor(255, 255, 255, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        self.Geometriadocordo.setPalette(palette2)
        self.label = QLabel(self.Geometriadocordo)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 20, 111, 31))
        palette3 = QPalette()
        brush5 = QBrush(QColor(162, 23, 51, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush5)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush5)
        self.label.setPalette(palette3)
        font = QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.formLayoutWidget = QWidget(self.Geometriadocordo)
        self.formLayoutWidget.setObjectName(u"formLayoutWidget")
        self.formLayoutWidget.setGeometry(QRect(160, 20, 191, 171))
        self.formLayout = QFormLayout(self.formLayoutWidget)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.lineEdit = QLineEdit(self.formLayoutWidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setEnabled(True)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)

        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.lineEdit)

        self.label_5 = QLabel(self.formLayoutWidget)
        self.label_5.setObjectName(u"label_5")
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        self.label_5.setPalette(palette4)

        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.label_5)

        self.lineEdit_2 = QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setObjectName(u"lineEdit_2")

        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.lineEdit_2)

        self.label_6 = QLabel(self.formLayoutWidget)
        self.label_6.setObjectName(u"label_6")
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        self.label_6.setPalette(palette5)

        self.formLayout.setWidget(2, QFormLayout.FieldRole, self.label_6)

        self.lineEdit_3 = QLineEdit(self.formLayoutWidget)
        self.lineEdit_3.setObjectName(u"lineEdit_3")

        self.formLayout.setWidget(4, QFormLayout.LabelRole, self.lineEdit_3)

        self.label_7 = QLabel(self.formLayoutWidget)
        self.label_7.setObjectName(u"label_7")
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        self.label_7.setPalette(palette6)

        self.formLayout.setWidget(4, QFormLayout.FieldRole, self.label_7)

        self.lineEdit_4 = QLineEdit(self.formLayoutWidget)
        self.lineEdit_4.setObjectName(u"lineEdit_4")

        self.formLayout.setWidget(5, QFormLayout.LabelRole, self.lineEdit_4)

        self.label_8 = QLabel(self.formLayoutWidget)
        self.label_8.setObjectName(u"label_8")
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        self.label_8.setPalette(palette7)

        self.formLayout.setWidget(5, QFormLayout.FieldRole, self.label_8)

        self.label_4 = QLabel(self.formLayoutWidget)
        self.label_4.setObjectName(u"label_4")
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush4)
        brush6 = QBrush(QColor(255, 85, 0, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette8.setBrush(QPalette.Active, QPalette.Light, brush6)
        brush7 = QBrush(QColor(85, 255, 255, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette8.setBrush(QPalette.Active, QPalette.Base, brush7)
        palette8.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        palette8.setBrush(QPalette.Inactive, QPalette.Light, brush6)
        palette8.setBrush(QPalette.Inactive, QPalette.Base, brush7)
        palette8.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette8.setBrush(QPalette.Disabled, QPalette.Light, brush6)
        palette8.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette8.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        self.label_4.setPalette(palette8)
        self.label_4.setStyleSheet(u"")

        self.formLayout.setWidget(6, QFormLayout.SpanningRole, self.label_4)

        self.lineEdit_5 = QLineEdit(self.formLayoutWidget)
        self.lineEdit_5.setObjectName(u"lineEdit_5")

        self.formLayout.setWidget(7, QFormLayout.LabelRole, self.lineEdit_5)

        self.label_9 = QLabel(self.formLayoutWidget)
        self.label_9.setObjectName(u"label_9")
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        self.label_9.setPalette(palette9)

        self.formLayout.setWidget(7, QFormLayout.FieldRole, self.label_9)

        self.label_3 = QLabel(self.formLayoutWidget)
        self.label_3.setObjectName(u"label_3")
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush4)
        palette10.setBrush(QPalette.Active, QPalette.Light, brush6)
        palette10.setBrush(QPalette.Active, QPalette.Base, brush7)
        palette10.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        palette10.setBrush(QPalette.Inactive, QPalette.Light, brush6)
        palette10.setBrush(QPalette.Inactive, QPalette.Base, brush7)
        palette10.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette10.setBrush(QPalette.Disabled, QPalette.Light, brush6)
        palette10.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette10.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        self.label_3.setPalette(palette10)
        self.label_3.setStyleSheet(u"")

        self.formLayout.setWidget(3, QFormLayout.SpanningRole, self.label_3)

        self.label_2 = QLabel(self.formLayoutWidget)
        self.label_2.setObjectName(u"label_2")
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.WindowText, brush4)
        palette11.setBrush(QPalette.Active, QPalette.Light, brush6)
        palette11.setBrush(QPalette.Active, QPalette.Base, brush7)
        palette11.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette11.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        palette11.setBrush(QPalette.Inactive, QPalette.Light, brush6)
        palette11.setBrush(QPalette.Inactive, QPalette.Base, brush7)
        palette11.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette11.setBrush(QPalette.Disabled, QPalette.Light, brush6)
        palette11.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette11.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        self.label_2.setPalette(palette11)
        self.label_2.setStyleSheet(u"")

        self.formLayout.setWidget(0, QFormLayout.SpanningRole, self.label_2)

        self.gridLayoutWidget = QWidget(self.Geometriadocordo)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(20, 230, 411, 241))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.label_22 = QLabel(self.gridLayoutWidget)
        self.label_22.setObjectName(u"label_22")
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette12.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        self.label_22.setPalette(palette12)

        self.gridLayout.addWidget(self.label_22, 8, 5, 1, 1)

        self.lineEdit_10 = QLineEdit(self.gridLayoutWidget)
        self.lineEdit_10.setObjectName(u"lineEdit_10")

        self.gridLayout.addWidget(self.lineEdit_10, 10, 1, 1, 1)

        self.label_11 = QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName(u"label_11")
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.WindowText, brush4)
        palette13.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        self.label_11.setPalette(palette13)

        self.gridLayout.addWidget(self.label_11, 0, 4, 1, 1)

        self.label_20 = QLabel(self.gridLayoutWidget)
        self.label_20.setObjectName(u"label_20")
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.WindowText, brush4)
        palette14.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        self.label_20.setPalette(palette14)

        self.gridLayout.addWidget(self.label_20, 7, 4, 1, 1)

        self.label_14 = QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName(u"label_14")
        palette15 = QPalette()
        palette15.setBrush(QPalette.Active, QPalette.WindowText, brush5)
        palette15.setBrush(QPalette.Inactive, QPalette.WindowText, brush5)
        self.label_14.setPalette(palette15)
        self.label_14.setFont(font)

        self.gridLayout.addWidget(self.label_14, 4, 0, 1, 1)

        self.lineEdit_8 = QLineEdit(self.gridLayoutWidget)
        self.lineEdit_8.setObjectName(u"lineEdit_8")

        self.gridLayout.addWidget(self.lineEdit_8, 6, 1, 1, 1)

        self.lineEdit_9 = QLineEdit(self.gridLayoutWidget)
        self.lineEdit_9.setObjectName(u"lineEdit_9")

        self.gridLayout.addWidget(self.lineEdit_9, 8, 1, 1, 1)

        self.label_19 = QLabel(self.gridLayoutWidget)
        self.label_19.setObjectName(u"label_19")
        palette16 = QPalette()
        palette16.setBrush(QPalette.Active, QPalette.WindowText, brush4)
        palette16.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        self.label_19.setPalette(palette16)

        self.gridLayout.addWidget(self.label_19, 5, 4, 1, 1)

        self.lineEdit_11 = QLineEdit(self.gridLayoutWidget)
        self.lineEdit_11.setObjectName(u"lineEdit_11")

        self.gridLayout.addWidget(self.lineEdit_11, 6, 4, 1, 1)

        self.lineEdit_13 = QLineEdit(self.gridLayoutWidget)
        self.lineEdit_13.setObjectName(u"lineEdit_13")

        self.gridLayout.addWidget(self.lineEdit_13, 10, 4, 1, 1)

        self.lineEdit_12 = QLineEdit(self.gridLayoutWidget)
        self.lineEdit_12.setObjectName(u"lineEdit_12")

        self.gridLayout.addWidget(self.lineEdit_12, 8, 4, 1, 1)

        self.label_13 = QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName(u"label_13")

        self.gridLayout.addWidget(self.label_13, 3, 0, 1, 1)

        self.label_18 = QLabel(self.gridLayoutWidget)
        self.label_18.setObjectName(u"label_18")
        palette17 = QPalette()
        palette17.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette17.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        self.label_18.setPalette(palette17)

        self.gridLayout.addWidget(self.label_18, 6, 5, 1, 1)

        self.label_17 = QLabel(self.gridLayoutWidget)
        self.label_17.setObjectName(u"label_17")
        palette18 = QPalette()
        palette18.setBrush(QPalette.Active, QPalette.WindowText, brush4)
        palette18.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        self.label_17.setPalette(palette18)

        self.gridLayout.addWidget(self.label_17, 7, 1, 1, 1)

        self.label_15 = QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName(u"label_15")
        palette19 = QPalette()
        palette19.setBrush(QPalette.Active, QPalette.WindowText, brush4)
        palette19.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        self.label_15.setPalette(palette19)

        self.gridLayout.addWidget(self.label_15, 5, 1, 1, 1)

        self.checkBox = QCheckBox(self.gridLayoutWidget)
        self.checkBox.setObjectName(u"checkBox")
        palette20 = QPalette()
        palette20.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette20.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        self.checkBox.setPalette(palette20)

        self.gridLayout.addWidget(self.checkBox, 2, 0, 1, 1)

        self.label_12 = QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName(u"label_12")
        palette21 = QPalette()
        palette21.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette21.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        self.label_12.setPalette(palette21)

        self.gridLayout.addWidget(self.label_12, 2, 5, 1, 1)

        self.lineEdit_7 = QLineEdit(self.gridLayoutWidget)
        self.lineEdit_7.setObjectName(u"lineEdit_7")

        self.gridLayout.addWidget(self.lineEdit_7, 1, 4, 1, 1)

        self.label_21 = QLabel(self.gridLayoutWidget)
        self.label_21.setObjectName(u"label_21")
        palette22 = QPalette()
        palette22.setBrush(QPalette.Active, QPalette.WindowText, brush4)
        palette22.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        self.label_21.setPalette(palette22)

        self.gridLayout.addWidget(self.label_21, 9, 4, 1, 1)

        self.label_16 = QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName(u"label_16")
        palette23 = QPalette()
        palette23.setBrush(QPalette.Active, QPalette.WindowText, brush4)
        palette23.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        self.label_16.setPalette(palette23)

        self.gridLayout.addWidget(self.label_16, 9, 1, 1, 1)

        self.horizontalSpacer = QSpacerItem(200, 30, QSizePolicy.MinimumExpanding, QSizePolicy.Minimum)

        self.gridLayout.addItem(self.horizontalSpacer, 1, 3, 1, 1)

        self.lineEdit_6 = QLineEdit(self.gridLayoutWidget)
        self.lineEdit_6.setObjectName(u"lineEdit_6")

        self.gridLayout.addWidget(self.lineEdit_6, 3, 1, 1, 1)

        self.label_10 = QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName(u"label_10")
        palette24 = QPalette()
        palette24.setBrush(QPalette.Active, QPalette.WindowText, brush5)
        palette24.setBrush(QPalette.Inactive, QPalette.WindowText, brush5)
        self.label_10.setPalette(palette24)
        self.label_10.setFont(font)

        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)

        self.label_24 = QLabel(self.gridLayoutWidget)
        self.label_24.setObjectName(u"label_24")
        palette25 = QPalette()
        palette25.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette25.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        self.label_24.setPalette(palette25)

        self.gridLayout.addWidget(self.label_24, 6, 2, 1, 1)

        self.label_25 = QLabel(self.gridLayoutWidget)
        self.label_25.setObjectName(u"label_25")
        palette26 = QPalette()
        palette26.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette26.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        self.label_25.setPalette(palette26)

        self.gridLayout.addWidget(self.label_25, 8, 2, 1, 1)

        self.PredicttionTabWidget.addTab(self.Geometriadocordo, "")
        self.altura = QWidget()
        self.altura.setObjectName(u"altura")
        palette27 = QPalette()
        palette27.setBrush(QPalette.Active, QPalette.Base, brush4)
        brush8 = QBrush(QColor(240, 222, 201, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette27.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette27.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette27.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        palette27.setBrush(QPalette.Disabled, QPalette.Base, brush8)
        palette27.setBrush(QPalette.Disabled, QPalette.Window, brush8)
        self.altura.setPalette(palette27)
        self.PredicttionTabWidget.addTab(self.altura, "")
        self.redes_neurais_geometria = QWidget()
        self.redes_neurais_geometria.setObjectName(u"redes_neurais_geometria")
        self.PredicttionTabWidget.addTab(self.redes_neurais_geometria, "")
        self.balanco_fase = QWidget()
        self.balanco_fase.setObjectName(u"balanco_fase")
        self.PredicttionTabWidget.addTab(self.balanco_fase, "")
        self.distancia_interdendritica = QWidget()
        self.distancia_interdendritica.setObjectName(u"distancia_interdendritica")
        self.PredicttionTabWidget.addTab(self.distancia_interdendritica, "")
        self.tamanho_grao = QWidget()
        self.tamanho_grao.setObjectName(u"tamanho_grao")
        self.PredicttionTabWidget.addTab(self.tamanho_grao, "")
        self.primaryTabWidget.addTab(self.tab1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tabWidget = QTabWidget(self.tab_2)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 800, 570))
        palette28 = QPalette()
        brush9 = QBrush(QColor(85, 170, 0, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette28.setBrush(QPalette.Active, QPalette.WindowText, brush9)
        palette28.setBrush(QPalette.Inactive, QPalette.WindowText, brush9)
        self.tabWidget.setPalette(palette28)
        self.melting_pool = QWidget()
        self.melting_pool.setObjectName(u"melting_pool")
        palette29 = QPalette()
        brush10 = QBrush(QColor(240, 149, 149, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette29.setBrush(QPalette.Active, QPalette.Window, brush10)
        palette29.setBrush(QPalette.Inactive, QPalette.Window, brush10)
        palette29.setBrush(QPalette.Disabled, QPalette.Base, brush10)
        palette29.setBrush(QPalette.Disabled, QPalette.Window, brush10)
        self.melting_pool.setPalette(palette29)
        self.tabWidget.addTab(self.melting_pool, "")
        self.bead_geometry = QWidget()
        self.bead_geometry.setObjectName(u"bead_geometry")
        palette30 = QPalette()
        brush11 = QBrush(QColor(232, 181, 146, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette30.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette30.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette30.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette30.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.bead_geometry.setPalette(palette30)
        self.tabWidget.addTab(self.bead_geometry, "")
        self.primaryTabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.primaryTabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.primaryTabWidget.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.primaryTabWidget.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.primaryTabWidget.addTab(self.tab_6, "")
        AMS_Interface.setCentralWidget(self.centralwidget)

        self.retranslateUi(AMS_Interface)

        self.primaryTabWidget.setCurrentIndex(0)
        self.PredicttionTabWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(AMS_Interface)
    # setupUi

    def retranslateUi(self, AMS_Interface):
        AMS_Interface.setWindowTitle(QCoreApplication.translate("AMS_Interface", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("AMS_Interface", u"Electric Parameters", None))
        self.label_5.setText(QCoreApplication.translate("AMS_Interface", u"(mm/s)", None))
        self.label_6.setText(QCoreApplication.translate("AMS_Interface", u"(m/min)", None))
        self.label_7.setText(QCoreApplication.translate("AMS_Interface", u"(mm/s)", None))
        self.label_8.setText(QCoreApplication.translate("AMS_Interface", u"(m/min)", None))
        self.label_4.setText(QCoreApplication.translate("AMS_Interface", u"Voltage", None))
        self.label_9.setText(QCoreApplication.translate("AMS_Interface", u"(V)", None))
        self.label_3.setText(QCoreApplication.translate("AMS_Interface", u"Travel Speed", None))
        self.label_2.setText(QCoreApplication.translate("AMS_Interface", u"Wire Feed Speed", None))
        self.label_22.setText(QCoreApplication.translate("AMS_Interface", u"(W/(m. \u00b0K)", None))
        self.label_11.setText(QCoreApplication.translate("AMS_Interface", u"Current", None))
        self.label_20.setText(QCoreApplication.translate("AMS_Interface", u"Thermal Conductivity", None))
        self.label_14.setText(QCoreApplication.translate("AMS_Interface", u"Physical properties", None))
        self.label_19.setText(QCoreApplication.translate("AMS_Interface", u"Density", None))
        self.label_13.setText("")
        self.label_18.setText(QCoreApplication.translate("AMS_Interface", u"(g/cm^3)", None))
        self.label_17.setText(QCoreApplication.translate("AMS_Interface", u"Specific Heat", None))
        self.label_15.setText(QCoreApplication.translate("AMS_Interface", u"Melting Point", None))
        self.checkBox.setText(QCoreApplication.translate("AMS_Interface", u"Fronius", None))
        self.label_12.setText(QCoreApplication.translate("AMS_Interface", u"(A)", None))
        self.label_21.setText(QCoreApplication.translate("AMS_Interface", u"Emissivity", None))
        self.label_16.setText(QCoreApplication.translate("AMS_Interface", u"Viscosity", None))
        self.label_10.setText(QCoreApplication.translate("AMS_Interface", u"Electric Current", None))
        self.label_24.setText(QCoreApplication.translate("AMS_Interface", u"(\u00b0C)", None))
        self.label_25.setText(QCoreApplication.translate("AMS_Interface", u"(cal/g. \u00b0C)", None))
        self.PredicttionTabWidget.setTabText(self.PredicttionTabWidget.indexOf(self.Geometriadocordo), QCoreApplication.translate("AMS_Interface", u"Geometria do cord\u00e3o", None))
        self.PredicttionTabWidget.setTabText(self.PredicttionTabWidget.indexOf(self.altura), QCoreApplication.translate("AMS_Interface", u"Altura das Camadas", None))
        self.PredicttionTabWidget.setTabText(self.PredicttionTabWidget.indexOf(self.redes_neurais_geometria), QCoreApplication.translate("AMS_Interface", u"Redes Neurais Geometria", None))
        self.PredicttionTabWidget.setTabText(self.PredicttionTabWidget.indexOf(self.balanco_fase), QCoreApplication.translate("AMS_Interface", u"Balan\u00e7o de Fase", None))
        self.PredicttionTabWidget.setTabText(self.PredicttionTabWidget.indexOf(self.distancia_interdendritica), QCoreApplication.translate("AMS_Interface", u"Dist\u00e2ncia Interdendr\u00edtica", None))
        self.PredicttionTabWidget.setTabText(self.PredicttionTabWidget.indexOf(self.tamanho_grao), QCoreApplication.translate("AMS_Interface", u"Tamanho de Gr\u00e3o", None))
        self.primaryTabWidget.setTabText(self.primaryTabWidget.indexOf(self.tab1), QCoreApplication.translate("AMS_Interface", u"Predi\u00e7\u00e3o", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.melting_pool), QCoreApplication.translate("AMS_Interface", u"Melting Pool", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.bead_geometry), QCoreApplication.translate("AMS_Interface", u"Bead Geometry", None))
        self.primaryTabWidget.setTabText(self.primaryTabWidget.indexOf(self.tab_2), QCoreApplication.translate("AMS_Interface", u"Measuring Tool", None))
        self.primaryTabWidget.setTabText(self.primaryTabWidget.indexOf(self.tab_3), QCoreApplication.translate("AMS_Interface", u"Thermal Cycles", None))
        self.primaryTabWidget.setTabText(self.primaryTabWidget.indexOf(self.tab_4), QCoreApplication.translate("AMS_Interface", u"Point Cloud Analysis", None))
        self.primaryTabWidget.setTabText(self.primaryTabWidget.indexOf(self.tab_5), QCoreApplication.translate("AMS_Interface", u"Thermal control systems", None))
        self.primaryTabWidget.setTabText(self.primaryTabWidget.indexOf(self.tab_6), QCoreApplication.translate("AMS_Interface", u"Instability and detect monitoring", None))
    # retranslateUi

